@startuml
set separator none
title User Management

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("LedgerlyApplication.LedgerlyApplication_boundary", "LedgerlyApplication", $tags="") {
  Component(LedgerlyApplication.LedgerlyApplication.UserManagement, "User Management", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml