@startuml
set separator none
title Config

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("LedgerlyApplication.LedgerlyApplication_boundary", "LedgerlyApplication", $tags="") {
  Component(LedgerlyApplication.LedgerlyApplication.Config, "Config", $techn="Module", $descr="", $tags="", $link="")
  Component(LedgerlyApplication.LedgerlyApplication.CustomerManagement, "Customer Management", $techn="Module", $descr="", $tags="", $link="")
  Component(LedgerlyApplication.LedgerlyApplication.InvoiceManagement, "Invoice Management", $techn="Module", $descr="", $tags="", $link="")
  Component(LedgerlyApplication.LedgerlyApplication.PaymentProcessing, "Payment Processing", $techn="Module", $descr="", $tags="", $link="")
}

Rel(LedgerlyApplication.LedgerlyApplication.Config, LedgerlyApplication.LedgerlyApplication.CustomerManagement, "depends on", $techn="", $tags="", $link="")
Rel(LedgerlyApplication.LedgerlyApplication.Config, LedgerlyApplication.LedgerlyApplication.InvoiceManagement, "depends on", $techn="", $tags="", $link="")
Rel(LedgerlyApplication.LedgerlyApplication.Config, LedgerlyApplication.LedgerlyApplication.PaymentProcessing, "depends on", $techn="", $tags="", $link="")
Rel(LedgerlyApplication.LedgerlyApplication.PaymentProcessing, LedgerlyApplication.LedgerlyApplication.InvoiceManagement, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml